name: Upload mcpack
on:
  release:
    types: [published]

jobs:
  upload-mcpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i

      - name: Build
        run: bun run build

      - name: Get Name
        id: get-name
        run: |
          NAME=$(jq -r '.header.name' manifest.json)
          echo "fileName=${NAME}.mcpack" >> $GITHUB_OUTPUT

      - name: Make Archive
        run: |
          zip -r ${{ steps.get-name.outputs.fileName }} manifest.json pack_icon.png scripts README.md LICENSE

      - name: Upload Release Asset
        run: |
          gh release upload ${{ github.event.release.tag_name }} ${{ steps.get-name.outputs.fileName }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
